---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - vagrant
    - geerlingguy.mysql 
    - mongo
    - rvm_io.rvm1-ruby
    - role: integration-test
      tags:
        - 'test'
  vars:
    mysql_root_password: password
    mysql_databases:
      - name: easy_e
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: easy_e
        host: "%"
        password: password
        priv: "*.*:SUPER"

    mysql_max_binlog_size: "100M"
    mysql_expire_logs_days: "10"
    mysql_replication_master: 'master'
    mysql_replication_user: 
      name: easy_e_slave
      host: "%"
      password: password

    mongod_smallfiles: "true"
    mongod_port: 27017
    mongod_repl_servers: ["master", "slave-wt", "slave-mmap"]
    mongod_repl_master: "master"
    mongod_replset_name: snap-ebs
    mongod_user: mongod
    mongod_bind_ip: 0.0.0.0

    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_rubies:
      - 'ruby-2.2.0'
