---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - vagrant
    # - mysql
    - bennojoy.mongo_mongod
    - rvm_io.rvm1-ruby
    - role: integration-test
      tags:
        - 'test'
  vars:
    mongod_smallfiles: "true"
    mongod_port: 2700
    mongod_replication: true
    mongod_repl_servers: ["master", "slave-wt", "slave-mmap"]
    mongod_repl_master: "master"
    mongod_replset_name: easy-e
    mongod_repo_debian: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse"
    mongod_pkgs:
      - python-selinux
      - mongodb-org
      - python-pymongo
    mongod_bind_ip: 0.0.0.0
    mongod_user: 'mongod'

    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_rubies:
      - 'ruby-2.2.2'
