---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - vagrant
    # - mysql
    - bennojoy.mongo_mongod
    - role: rvm_io.rvm1-ruby
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
      rvm1_rubies:
        - 'ruby-2.2.2'
