---
- hosts: all
  remote_user: vagrant
  sudo: yes
  roles:
    - vagrant
    # - mysql
    - mongo
    - rvm_io.rvm1-ruby
    - role: integration-test
      tags:
        - 'test'
  vars:
    mongod_smallfiles: "true"
    mongod_port: 27017
    mongod_repl_servers: ["master", "slave-wt", "slave-mmap"]
    mongod_repl_master: "master"
    mongod_replset_name: snap-ebs
    mongod_user: mongod
    mongod_bind_ip: 0.0.0.0

    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_rubies:
      - 'ruby-2.2.0'
