---
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible
# hosts inventory for a source. Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html

- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_eth1.ipv4.address is defined
  with_items: groups['all']

- shell: ruby --version | cut -f 2 -d ' ' | sed -e 's/\([0-9.]*\).*/\1/'
  register: ruby_version_check
  changed_when: false

- include: ruby.yml
  when: ruby_version_check.stdout | version_compare(ruby_version, operator='!=')