---
# Idempotent way to build a /etc/hosts file with Ansible using your Ansible
# hosts inventory for a source. Will include all hosts the playbook is run on.
# Inspired from http://xmeblog.blogspot.com/2013/06/ansible-dynamicaly-update-etchosts.html
- name: "Build hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ (hostvars[item].ansible_all_ipv4_addresses | ipaddr("192.168.10.0/24"))[0] }} {{item}}" state=present
  with_items: groups['all']
