---
- include: prepare-for-test.yml

- name: prevent mongod from restarting
  shell: chmod -x `which mongod`

- name: 'run against a server that fails to restart'
  shell: bash -lc './bin/easy-e -a 'dummy' -s 'dummy' -m --mongo --mongo-port 2700 --mongo-shutdown yes --mongo-service mongodb-2700 --mongo-user {{ mongod_user }} --mongo-password {{ mongod_password }} --mongo-server-selection-timeout 1 --mongo-connection-timeout 1 --mongo-socket-timeout 1 ' chdir=/home/{{ ansible_ssh_user }}/easy-e
  register: test_output
  ignore_errors: true

- include: print-results.yml

- assert:
    that: test_output|succeeded
    that: '"ERROR" in test_output.stdout'
    that: '"still accessible" in test_output.stdout'
