---
# tasks file for integration-test
- name: 'Check for Bundler'
  shell: bash -lc 'which bundler'
  register: bundler_check
  ignore_errors: true
  changed_when: bundler_check|failed

- name: 'Install Bundler'
  shell: bash -lc 'gem install bundler'
  when: bundler_check|failed

- name: 'Install needed system libs'
  apt: name={{ item }}
  with_items:
  - libmysqlclient-dev

- name: 'bundle install'
  shell: bash -lc 'bundle install' chdir=/home/{{ ansible_ssh_user }}/easy-e

- name: 'ensure mongo is running'
  service: name=mongodb-2700 state=started

- name: 'run the tests!'
  shell: bash -lc './bin/easy-e -a 'dummy' -s 'dummy' -m --mongo --mongo-port 2700 --mongo-shutdown yes --mongo-service mongodb-2700' chdir=/home/{{ ansible_ssh_user }}/easy-e
  register: test_output

- name: 'results (stdout):'
  debug: var=test_output.stdout_lines

- name: 'results (stderr):'
  debug: var=test_output.stderr_lines