---
# tasks file for integration-test
- name: 'Install needed system libs'
  apt: name={{ item }}
  when: 
  with_items:
  - libmysqlclient-dev
  - socat
  when: ansible_os_family == "Debian"

- name: Determine whether this is a master node
  set_fact: i_am_master="{{ (mongod_repl_master == inventory_hostname) or (mongod_repl_master == ansible_hostname) }}"

- name: 'Install needed system libs'
  yum: name={{ item }} state=installed
  with_items:
  - mariadb-devel
  - socat
  when: ansible_os_family == "RedHat"

- name: 'bundle install'
  shell: bash -lc 'bundle install' chdir=/home/{{ ansible_ssh_user }}/snap-ebs

- name: 'read mongodb password'
  shell: cat /tmp/mongod_password
  register: mongod_password_content
  when: mongod_password is not defined

- name: 'set mongodb password'
  set_fact: mongod_password={{ mongod_password_content.stdout }}
  when: mongod_password is not defined

- include: nominal.yml

- include: fail-to-restart.yml
  when: mongod_storage_engine == 'wiredTiger'

- include: report-successful-restart-but-still-unavailable.yml
  when: mongod_storage_engine == 'wiredTiger'
