---
# tasks file for integration-test
- name: 'Check for Bundler'
  shell: bash -lc 'which bundler'
  register: bundler_check
  ignore_errors: true
  changed_when: bundler_check|failed

- name: 'Install Bundler'
  shell: bash -lc 'gem install bundler'
  when: bundler_check|failed

- name: 'Install needed system libs'
  apt: name={{ item }}
  with_items:
  - libmysqlclient-dev
  - socat

- name: 'bundle install'
  shell: bash -lc 'bundle install' chdir=/home/{{ ansible_ssh_user }}/easy-e

- name: 'read mongodb password'
  shell: cat /tmp/mongod_password
  register: mongod_password_content
  when: mongod_password is not defined

- name: 'set mongodb password'
  set_fact: mongod_password={{ mongod_password_content.stdout }}
  when: mongod_password is not defined

- include: nominal.yml

- include: fail-to-restart.yml
  when: mongod_storage_engine == 'wiredTiger'

- include: report-successful-restart-but-still-unavailable.yml
  when: mongod_storage_engine == 'wiredTiger'
