---
- include: prepare-for-test.yml

- name: 'run against a setup in nominal condition'
  shell: bash -lc './bin/easy-e -a 'dummy' -s 'dummy' -m --mongo --mongo-port {{ mongod_port }} --mongo-shutdown yes --mongo-service mongod --mongo-user mongod --mongo-password {{ mongod_password }}' chdir=/home/{{ ansible_ssh_user }}/easy-e
  register: test_output

- include: print-results.yml
