---
- include: prepare-for-test.yml

- name: 'run against a setup in nominal condition'
  shell: bash -lc './bin/snap-ebs -a 'dummy' -s 'dummy' -m --mongo --mongo-port {{ mongod_port }} --mongo-shutdown yes --mongo-user mongod --mongo-password {{ mongod_password }}' chdir=/home/{{ ansible_ssh_user }}/snap-ebs
  register: test_output
  async: 10
  poll: 5

- include: print-results.yml

- assert:
    that: '"ERROR" not in test_output.stdout'
  when: not i_am_master

- assert:
    that: '"ERROR" in test_output.stdout'
    that: '"appears to be a primary member" in test_output.stdout'
  when: i_am_master
